name: FactionsExtra
main: com.mutinycraft.jigsaw.FactionsExtra.FactionsExtra
version: 1.2
author: Jigsaw
description: Extra features added to work alongside the Factions plugin.

depend: [Factions, TagAPI]

commands:
   factionscore:
      aliases: fscore
      description: Main command.
      usage: /factionscore [Faction Name]
      
   factiontier:
      aliases: ftier
      description: Change the tier of a faction.
      usage: /factiontier [Faction Name] [Tier]
      
   factiontop:
      aliases: ftop
      description: List of top 10 factions.
      usage: /factiontop