name: FactionsExtra
main: com.mutinycraft.jigsaw.FactionsExtra.FactionsExtra
version: 1.3
author: Jigsaw
description: Extra features added to work alongside the Factions plugin.

depend: [Factions]
softdepend: [TagAPI]

commands:
   factionscore:
      aliases: fscore
      description: Main command.
      usage: /factionscore [Faction Name]
      
   factiontier:
      aliases: ftier
      description: Change the tier of a faction.
      usage: /factiontier [Faction Name] [Tier]
      
   factiontop:
      aliases: ftop
      description: List of top 10 factions.
      usage: /factiontop
      
   factionreset:
      aliases: freset
      description: Resets the factions score to 0.
      usage: /factionreset